### ISSUE TITLE
Auto-import /components

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-tailwind#14]
Right now, `tailwind/components` need to be manually imported. Let's figure out a way to automatically import them.

**Comment by samselikoff** [comment]
16ddd6bd9c06a8819a4a63c8a64a6a27b91188ee closes

**Comment by scottmessinger** [comment]
Thanks for this add on! When I try to import from `tailwind/components`, nothing is loaded -- that part of the compiled stylesheet has nothing in it. Any idea what's going on or why?

**Comment by scottmessinger** [comment]
I can look to reproduce, but I figured I'd just ask in case there's a simple solution I'm not thinking of.

**Comment by scottmessinger** [comment]
Looks like I narrowed down the problem -- if `@import "./components/button";` is *before* any of the `@tailwind ...`, it works. If I move it after, it doesn't work. I'm wondering if this is related to https://github.com/TrySound/postcss-easy-import/issues/24

**Comment by samselikoff** [comment]
@scottmessinger sorry about the delayed response!

You shouldn't have to `@import "./components/button"`... [this line](https://github.com/embermap/ember-cli-tailwind/blob/091c6e69ca094d8fbeeedd091b045552ce56733d/blueprints/ember-cli-tailwind/files/__root__/tailwind/modules.css#L38) should auto import the entire directory. I assume that's not working?

**Comment by scottmessinger** [comment]
Yup! That's not working. I'll work on a reproduction.

**Comment by samselikoff** [comment]
@scottmessinger try 0.5.1, it might fix your issue
