### ISSUE TITLE
Tailwind v1.0 is out

### ISSUE THREAD

**Issue by raido** [embermap/ember-cli-tailwind#143]
Tailwind just recently hit v1.0 milestone. This addon should be updated to reflect that aswell.

**Comment by samselikoff** [comment]
definitely 👍 I think it's going to involve a bit of re-working. Not sure we want to scaffold out the entire config folder structure anymore, since 1.0 is nudging folks to lean on the default config as much as possible.

**Comment by barryofguilder** [comment]
So it seems that at a minimum, this addon would really only be responsible for generating the Tailwind styles and then watching the Tailwind config (if it exists in the project) for changes to recompile.

**Comment by rwwagner90** [comment]
@samselikoff did you decide on a path forward here? I am happy to help with things, if changes need to be made.

**Comment by samselikoff** [comment]
Not completely but been chatting with Jason a bit about it. I think this Addon should basically bootstrap an ember cli postcss pipeline for the host app, possibly with purge. Or maybe if that’s simple enough we should write a post somewhere and deprecate this?

**Comment by rwwagner90** [comment]
@samselikoff I am not sure what would be best. I defer to your expertise 😃

**Comment by nrcjbarry** [comment]
@rwwagner90 Chris Masters created this really awesome repo as a way to document how to use Tailwind 1.0 with Ember.js:

https://github.com/chrism/emberjs-tailwind-purgecss

**Comment by barryofguilder** [comment]
@rwwagner90 Chris Masters wrote this awesome repo to show how to use Tailwind 1.0 with Ember.js:

https://github.com/chrism/emberjs-tailwind-purgecss

**Comment by rwwagner90** [comment]
@barryofguilder is there anything that approach does not do that ember-cli-tailwind does?  If not, do you think we should build all of this into ember-cli-tailwind or should we deprecate in favor of people following that guide? I personally like when addons handle all this for me, and it's just a simple install command, but some people dislike the magic approach.

**Comment by barryofguilder** [comment]
@rwwagner90 I know that `ember-cli-tailwind` added a style guide, but I'm not sure if that was a widely used feature. I never used it because we had our own style guide we used.

I do think that it would be awesome if `ember-cli-tailwind` wired up the postcss config for you, but I'm not sure how it would work if the consuming app was already using postcss.

**Comment by raido** [comment]
I like the style guide. It is true that if you work on your project everyday you simply remember the classes. But for new people on team etc. it can be helpful to get going.

**Comment by CvX** [comment]
The style guide could be extracted to its own addon.

Though, imo that would be best handled by IDE extensions (like [vscode-tailwindcss](https://github.com/bradlc/vscode-tailwindcss), [vscode-tailwind-docs](https://github.com/austenc/vscode-tailwind-docs) or [autocomplete-tailwind](https://github.com/vinkla/autocomplete-tailwind)), i.e. they could generate the docs from the current app's config.

Also, the other thing that https://github.com/chrism/emberjs-tailwind-purgecss doesn't do is rebuilding the CSS when changes to tailwind's config are detected.

**Comment by barryofguilder** [comment]
@CvX Oh, good catch! Yeah, when I implemented Tailwind 1.0 into my Ember app, I put it in `app/tailwind/config.js`, so it did get rebuilt on change.

**Comment by chrism** [comment]
@Cvx @barryofguilder I've updated the guide now to include the config in the `app` directory — thanks for the feedback!

https://github.com/chrism/emberjs-tailwind-purgecss/commit/1a4c806b5bfe40db12e14d18e735bccdfa93811a

**Comment by yratanov** [comment]
@chrism you guide works fine for a new project, but in my case it's an existing project and with ember-component-css, with `.scss` files, which has some issues with `postcss-sass`: https://github.com/jeffjewiss/ember-cli-postcss/issues/143...

In the same time `ember-cli-tailwind` works without any problems on my project... 

So my vote is for supporting this addon and upgrading to tailwind v1.

**Comment by stephencattaneo** [comment]
Whats up with ember-cli-tailwind?  Reading the above I get the sense that this addon is essentially dead.  The instructions in the README.md for https://github.com/chrism/emberjs-tailwind-purgecss seem fairly complete.

**Comment by samselikoff** [comment]
It's not dead, but I think I need some guidance about the best way to proceed forward.

I think if I could snap my fingers, installing this addon would basically wire up the postcss pipeline a la Chris' example. But making that install idempotent involves a lot.

I do intend to address this, but it's lower priority than some other work I have right now.

**Comment by stephencattaneo** [comment]
cool 😎 FWIW I think the styleguide is super helpful.

ember-cli-sass doesn't have an explicit package.json dependency on the `sass` module, but does check for the existence of `sass` when the user tries to build ember.  https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L39

Perhaps that would be a good way forward of not explicitly depending on tailwind.

**Comment by samselikoff** [comment]
yah. I think it might be good to have it be a peerDependency.

The real big question is just how to bootstrap the postcss pipeline for folks while still exposing it. Maybe we can run a default one but if/when someone installs postcss themselves we just delegate to that.

**Comment by samselikoff** [comment]
I think we should probably deprecate this addon. I can't really think of a great way to automatically wire up postcss + tailwind, without exposing the pieces to the user so they can add autoprefixer, purgecss, etc.

I think we should point folks to [@chrism's setup guide](https://github.com/chrism/emberjs-tailwind-purgecss), and generally I think folks should probably take the time to learn how the pieces work. Addons like this tend to atrophy and block users from upgrading. I think going forward we should strive to integrate directly with packages in our Ember apps, so we can follow their upgrade guides and release notes.

If the styleguide is interesting we can make that a separate package, but tbh I thought I'd use it more but really don't. I think it's probably better for folks to get comfortable with tailwind's own docs site.

Thoughts?

**Comment by barryofguilder** [comment]
I agree. It was really straight forward to pull Tailwind 1.0 into our Ember app following the Tailwind docs as well as going through a guide like @chrism's.

**Comment by samselikoff** [comment]
@barryofguilder good to hear. Did you use ember-cli-postcss?

**Comment by samselikoff** [comment]
I am sad that there won't be a one-line command that gets a new Ember app wired up with Tailwind, but honestly if I were doing a quick demo I'd probably just drop the CDN link into index.html.

**Comment by barryofguilder** [comment]
@samselikoff I did. This is what our postcss config looks like:

```
postcssOptions: {
  compile: {
    plugins: [
      {
        module: require('postcss-import'),
        options: {
          path: ['node_modules'],
        },
      },
      require('tailwindcss')('app/tailwind/config.js'),
      require('autoprefixer'),
    ],
  },
}
```

**Note:** I'll be adding `purgecss` to this soon, just haven't got around to getting it on our list.

**Comment by rwwagner90** [comment]
What if this addon were turned into just blueprints to do this stuff for you directly in the app?

**Comment by samselikoff** [comment]
@rwwagner90 more to maintain & fall behind, hard to make it idempotent, etc. Maybe just better as a script folks can copy?

I'm happy to look at / merge the blueprints solution if you or someone else wants to experiment with it!

**Comment by raido** [comment]
Closing this issue as Tailwind documentation has setup steps for Ember with postCSS outlined - https://tailwindcss.com/docs/installation#build-tool-examples
