### ISSUE TITLE
Set buildTarget automatically

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-tailwind#16]
The way this addon works is by reading in a `/tailwind` directory and adding a built `tailwind.css` file to the build. There are actually three situations in which this can occur:

1. *An app*, via the `/app/tailwind/` directory. The `tailwind.css` file is added to the app's `app.css` file.
2. *An addon*, via the `/addon/tailwind/` directory. The `tailwind.css` file is added to the host app's `vendor.css` file.
3. *An addon*, via the `/test/dummy/app/tailwind/` directory (i.e. an addon's Dummy app). The `tailwind.css` file is added to the dummy app's `app.css` file.

Currently these are controlled via the `buildTarget` ENV option as described [in this release](https://github.com/embermap/ember-cli-tailwind/releases/tag/v0.3.0).

If we can find a reliable way for the code that runs in `index.js` to know whether it is being run in situation #1, #2, or #3 above, we could eliminate this configuration step and ship the addon with smart defaults.

From my perspective, here are the ideal flows:

**An app**
You run `ember install ember-cli-tailwind`. The generator adds the `/tailwind` directory to `app/tailwind`. That's it - `ember s` would automatically detect the new directory and know to build Tailwind for the app.

**An addon**
You run `ember install ember-cli-tailwind`. The generator adds the `/tailwind` directory to `addon/tailwind` by default. If you just want to style your components and ship those styles to host apps, that's it - ember-cli-tailwind would know to package those up and throw them in `vendor.css`.

If you want to use tailwind to style your addon's dummy app, you can re-run the generator using `ember g ember-cli-tailwind --dummy`, which will put the `/tailwind` directory in `/tests/dummy/app/tailwind`.

Ember CLI Tailwind could autodetect the presence of the `/tailwind` directory in both `/addon/tailwind` and `/tests/dummy/app/tailwind`, and do the right thing for each configuration.

---

I would love to have some help with this, if anyone wants to take it on!

**Comment by cafreeman** [comment]
@samselikoff Yea, this seems like a pretty reasonable approach, especially since we're already making other inferences based on the presence/absence of `tailwind.js`.

Is there a Broccoli-ish way of doing this, or would you just use `fs.existsSync`?

**Comment by samselikoff** [comment]
Probs just `fs.existsSync` 👍

**Comment by gossi** [comment]
Pssst. With MU this will always be `src/tailwind` (for `app`, `addon` and `engine`). I just tried. `ec-tailwind` becomes completely confused.

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-cli-tailwind/pull/35 closes this issue and we're tracking MU feature/bugs in other tickets. Hoping to get to it soon!
