### ISSUE TITLE
0.5.x generator introduces build error

### ISSUE THREAD

**Issue by jrowlingson** [embermap/ember-cli-tailwind#25]
It appears that changes related to https://github.com/embermap/ember-cli-tailwind/pull/24 may have introduced a build error.

This can be reproduced with the following steps:

* generate a new app via `ember new`
* install the latest changes from master via `ember i https://github.com/embermap/ember-cli-tailwind#master`
* run the addon's blueprint via `ember g ember-cli-tailwind`
* run the development server via `ember s` and observe the following error:

``` 
 - broccoliBuilderErrorStack: TypeError: e-test/tailwind/config/tailwind.js: Property callee of CallExpression expected node to be of a type ["Expression"] but instead got null
```

This was tested with the following versions:

```
❯ ember -v                                                                                                                                           ✗ master
ember-cli: 3.1.4
node: 9.3.0
os: darwin x64
```

It's unclear to me what the specific issue is here but I am noticing the following line appears to be causing trouble:

https://github.com/embermap/ember-cli-tailwind/pull/24/files#diff-1c826c5a208d7289f7efbca979da9db7R123

@jpadilla do you have any thoughts here?

**Comment by jpadilla** [comment]
@jrowlingson ahh good catch! It seems like I fixed this on the dummy app manually.

https://github.com/embermap/ember-cli-tailwind/pull/24/files#diff-f29fa2de49d2b2a36446ffe047bbc419

Will open a PR with fix now.

**Comment by jpadilla** [comment]
Just opened #26 with the fix. Feel free to try installing from it and check if it fixes the issue for you.
