### ISSUE TITLE
Tailwind styles are available in the app consuming the addon, but not the addon's dummy app

### ISSUE THREAD

**Issue by qpowell** [embermap/ember-cli-tailwind#28]
## Background

The issue title may not be the most helpful (sorry) so here's a brief example of what I'm working on and looking to accomplish.

I have an Ember addon that serves as a component library. In the component library, we use `ember-cli-addon-docs` to document component APIs and behavior. Lastly, we have an Ember app that use the components provided by the component library.

## The Issue

When using the addon's components in our Ember app, the tailwind styles work as expected. 👌🏾

When viewing the components inside of the addon's dummy apps, the styles don't appear to be loaded at all. 😭

## Reproduction

I've created an example addon and ember app the mirrors my current project setup.

[Example Addon with ember-cli-tailwind and ember-cli-addon-docs](https://github.com/qpowell/addon-with-docs)

[Example App that uses the 'Example Addon'](https://github.com/qpowell/addon-consumer)

I'm willing to provide any additional about my setup/configuration that may be useful for digging into this.

Thanks!

**Comment by samselikoff** [comment]
Seems like a bug.. you have `buildTarget` set to `addon` in Example Addon?

**Comment by qpowell** [comment]
Yeah, here's the contents of Example Addon's `index.js`

```javascript
'use strict';

module.exports = {
  name: 'addon-with-docs',
  options: {
    'ember-cli-tailwind': {
      buildTarget: 'addon'
    }
  }
};
```

And the `ember-cli-build.js` for the dummy app looks like this:

```javascript
module.exports = function(defaults) {
  let app = new EmberAddon(defaults, {
    // Add options here
    'ember-cli-tailwind': {
      buildTarget: 'dummy',
    }
  });

  /*
    This build file specifies the options for the dummy test app of this
    addon, located in `/tests/dummy`
    This build file does *not* influence how the addon or the app using it
    behave. You most likely want to be modifying `./index.js` or app's build file
  */

  return app.toTree();
};
```

**Comment by samselikoff** [comment]
I don't think you should have `buildTarget: 'dummy'` set, because that would mean the `/tailwind` dir should apply to your dummy app directly... I think you want it to apply to your addon, then have your dummy app import/consume those styles in the exactly same way an External app would. Does that make sense?

**Comment by qpowell** [comment]
Yeah, that makes sense. I think I misunderstood the "Addons, when styling things under /tests/dummy/app, your addon's dummy app" section in the README. 

To clarify, what's a valid use case where you'd set `buildTarget: 'dummy'` in the dummy app's `ember-cli-build.js`?

**Comment by samselikoff** [comment]
That's if you're installing Tailwind for the purpose of styling your dummy app... so it's as if your dummy app was its own Ember app and you ran `ember install ember-cli-tailwind` there. The `/tailwind` directory would be under `/tests/dummy/app/tailwind`.

 I know it's confusing, we want to set `buildTarget` automatically in the future.

**Comment by GavinJoyce** [comment]
@qpowell I'm trying to do something similar, but I haven't managed to get it working following your instructions above. Perhaps you might update your demo repos with your change that makes it work?

**Comment by qpowell** [comment]
@GavinJoyce yeah, I can do that tomorrow! For some context on what's going on, what part, in particular, are you having trouble with?

In the dummy app's `tailwind/modules.css`, I just imported the `modules.css` from the addon using its relative path. I'm assuming you have `buildTarget: 'dummy'` set in the dummy app?

**Comment by GavinJoyce** [comment]
@qpowell Thanks. I'm trying to make tailwind classes available in my addon (so that they can be used in consuming apps) and in my dummy app. I couldn't manage to get the dummy app to work following your instructions.

I'll create a PR for your addon repo above and see if it works there

**Comment by GavinJoyce** [comment]
It works: https://github.com/qpowell/addon-with-docs/pull/1

I must have done something wrong in my addon, I'll try again

**Comment by GavinJoyce** [comment]
It turns out I was missing `this._super(...arguments);` in the `included` hook in `index.js`. Everything is working well now

**Comment by samselikoff** [comment]
@GavinJoyce glad you got it working!

@qpowell are you still having this issue?

**Comment by qpowell** [comment]
@samselikoff I'm good, we can close this. Glad it stayed open long enough to help someone else out :)

**Comment by allthesignals** [comment]
> That's if you're installing Tailwind for the purpose of styling your dummy app... so it's as if your dummy app was its own Ember app and you ran ember install ember-cli-tailwind there. The /tailwind directory would be under /tests/dummy/app/tailwind.
>
> I know it's confusing, we want to set buildTarget automatically in the future.

What's the procedure for this use case? I want to make sure I'm doing this correctly... for example, I can use Tailwind styles in my dummy app, but I can't seem to get the tailwind components to work - even arbitrary classes I make don't get picked up. 

Thanks!

**Comment by samselikoff** [comment]
@allthesignals sounds like it could be a separate problem - I'll open another issue for it.

**Comment by Alonski** [comment]
Regarding this issue.
I am still not sure exactly what needs to be done to use `ember-cli-tailwind` in an addons dummy app.
What I ended up doing is creating this file:
`tests\dummy\app\tailwind\modules.css`
```scss
@import "../../../addon/tailwind/modules.css";
```

This seemed to do the trick, but I am not sure it is the best way to do this. Maybe there can be documentation on this?
