### ISSUE TITLE
Extract the style guide into an addon

### ISSUE THREAD

**Issue by jrowlingson** [embermap/ember-cli-tailwind#29]
This change would allow folks to provide a customized style guide without the need to maintain a fork.

**Comment by samselikoff** [comment]
Any chance you could share a screenshot of your styleguide? Curious if they're very specific changes or more like the kinds of things that should be merged in with the main one.

I think even if we don't extract the styleguide into an addon (not sold on that right this minute) we should make it easier to configure.

**Comment by jrowlingson** [comment]
Sure - at the moment it is simply a re-skin so there is nothing significant to share yet unfortunately. What we would like to do, however, is take it a bit more in the direction of the Tachyons [style guide](http://tachyons.io/docs/) with routes for each section. We would also like to experiment with providing some additional components to visualize the values (e.g. a [color stack component](https://tailwindcss.com/docs/colors#default-color-palette) .

But above that, what we are aiming for is to bring a level of "branding" to the style guide itself - i.e. something that harmonizes with the design system it is intended to document. This is an important part of the message to get buy-in from a designers point of view.

I suspect that this may be a fairly common use case but there may be better approach to satisfying the need. 

<img width="1045" alt="screen shot 2018-05-23 at 3 41 58 pm" src="https://user-images.githubusercontent.com/3051781/40448045-5bbad7d6-5ea2-11e8-898b-a16a73d9367f.png">

**Comment by samselikoff** [comment]
I love the color stack component idea. I agree branding is going to be desirable...

I think we should provide some container components/modules that have all the data needed to build a custom styleguide. I still like the lib having the default styleguide available out of the box, I think keeping it in the addon would make it easier to develop. We should make it opt-outable for folks who want to customize it.

**Comment by jrowlingson** [comment]
> I think we should provide some container components/modules that have all the data needed to build a custom styleguide.

This sounds like an appealing approach. I also agree that keeping it in the addon makes it a bit easier to work with. Closing in favor of https://github.com/embermap/ember-cli-tailwind/issues/33
