### ISSUE TITLE
Build error and custom components not included

### ISSUE THREAD

**Issue by smackesey** [embermap/ember-cli-tailwind#32]
I get the following build error even in a brand new Ember CLI app:

Could not load tailwindcss/plugins/container (imported by /Users/smackesey/stm/code/apps/ember/stmpd/tmp/rollup-cache_path-v3by5pPQ.tmp/build/config/tailwind.js): ENOENT: no such file or directory, open 'tailwindcss/plugins/container'

Also, my custom components and utilities are not available, and don't seem to be showing up in the `dist/assets/tailwind.css` directory.

**Comment by samselikoff** [comment]
@dfreeman I've tracked this down to some of our previous work on turning Tailwind's CJS modules into ES6 modules.

This line in the generated config imports the `container` plugin: 

https://github.com/embermap/ember-cli-tailwind/blob/master/blueprints/ember-cli-tailwind/files/__root__/tailwind/config/tailwind.js#L1

but that's actually coming from the `tailwindcss` node module. So when Rollup goes to roll `tailwind.js` up, it can't find this file and it breaks.

Any ideas on how we should approach fixing this?

**Comment by dfreeman** [comment]
We could probably use [`rollup-plugin-node-resolve`](https://github.com/rollup/rollup-plugin-node-resolve) (and maybe [`rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs), depending on how Tailwind is distributed) to get that included properly...

**Comment by samselikoff** [comment]
Gotcha. I'll give it a shot!

**Comment by samselikoff** [comment]
@smackesey Could you try 0.5.1 and see if it fixes?

**Comment by samselikoff** [comment]
@dfreeman that seemed to work - thank you very much for the tip!

**Comment by dfreeman** [comment]
👍 Honestly it was a bit of a shot in the dark—glad it worked!

**Comment by samselikoff** [comment]
This should be fixed so I'm closing for now - happy to reopen if folks are still having trouble!
