### ISSUE TITLE
Update tailwindcss to 0.6.x

### ISSUE THREAD

**Issue by jrowlingson** [embermap/ember-cli-tailwind#38]
Related https://github.com/embermap/ember-cli-tailwind/issues/23

**Comment by jpadilla** [comment]
PR incoming

**Comment by jpadilla** [comment]
Addressed this via https://github.com/embermap/ember-cli-tailwind/pull/40

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-cli-tailwind/pull/40 closes
