### ISSUE TITLE
can LESS work? 

### ISSUE THREAD

**Issue by deanmraz** [embermap/ember-cli-tailwind#44]
# Issue 
- Including `@import 'tailwind.css';` in app.less file does not work 

# Goal 
- being able to develop component files with less `./components/*.less` 

# Other Approach 
- This setup works with Edward's approach [outlined in this video](https://www.youtube.com/watch?v=h-0585O25HI). 
- [Example tailwind / less](https://github.com/deanmraz/tailwind-less/pull/2/files)

Hopefully, I'm doing it wrong, but let me know if this can be supported.

**Comment by samselikoff** [comment]
Looks like LESS's default inlining doesn't support certain CSS comments, which may be breaking your `@import` rule.

Try this:

```less
@import (inline) 'tailwind.css';
```

**Comment by brasilikum** [comment]
I can confirm that this works for me!

**Comment by deanmraz** [comment]
Thanks guys!
