### ISSUE TITLE
How do I add a plugin?

### ISSUE THREAD

**Issue by allthesignals** [embermap/ember-cli-tailwind#47]
Tailwind has a [plugins](https://tailwindcss.com/docs/plugins) system, but I'm not sure how to add a plugin. Is it something that goes in ember-cli-build or `environment.js`?

**Comment by allthesignals** [comment]
1. Open `app/tailwind/config/tailwind.js`

2. Import the Tailwind plugin after installing:
`import glhdTailwindcssTransitions from 'glhd-tailwindcss-transitions'`

3. Add the plugin to the `plugins` array in `tailwind.js`:
```javascript
  plugins: [
    container({
      // center: true,
      // padding: '1rem',
    }),
    glhdTailwindcssTransitions(),
  ],
```

**Comment by samselikoff** [comment]
👍 Glad you figured it out! This should definitely make it into the docs.

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-cli-tailwind/commit/27a8b6200e0aef316297e43b721b4e7651b23f1b
