### ISSUE TITLE
Add test for Tailwind custom utilities and components in all 3 build environments

### ISSUE THREAD

**Issue by samselikoff** [embermap/ember-cli-tailwind#50]
https://github.com/embermap/ember-cli-tailwind/issues/28#issuecomment-413717287

**Comment by allthesignals** [comment]
Happy to put a smaller repo together, but [here's](https://github.com/NYCPlanning/ember-mapbox-composer/tree/5ad4c244ebecd150e9f11555f393afffb7c8d196) where I'm seeing this.

**Comment by samselikoff** [comment]
https://github.com/embermap/ember-cli-tailwind/commit/994694a8d1d118ff1365fa768200a7f28ed049e5 closes
