### ISSUE TITLE
"Empty" styleguide page on ember 3.4

### ISSUE THREAD

**Issue by Windvis** [embermap/ember-cli-tailwind#63]
Hey guys,

I just installed the addon in an Ember 3.4 project and I noticed the styleguide is not working as expected. It just [displays a blank page](https://user-images.githubusercontent.com/3533236/48005336-76e2bf80-e113-11e8-9b31-b5411e4ea3bd.png).

I debugged it a bit and it seems to be caused by the template only `etw/module-section` component. It doesn't use the `@` argument syntax to retrieve values. I'm not sure when the backup lookup mechanism changed, but it doesn't seem to be working anymore.

Changing all arguments to use @ fixes the problem.

Did anyone else have this problem? Or does this depend on something in the parent project?

**Comment by samselikoff** [comment]
Thanks for reporting, going to be getting to our oss issues very soon :)

**Comment by Windvis** [comment]
It's a quick fix, I can provide a PR. But any idea what changed in Ember?

**Comment by Windvis** [comment]
It seems that I misunderstood the problem. I didn't know it was possible to create components without a js file, without them being a `template only component`.
