### ISSUE TITLE
Possible malicious dependency

### ISSUE THREAD

**Issue by ef4** [embermap/ember-cli-tailwind#65]
This package depends recursively on `event-stream`, which has malicious versions floating about. See:

https://github.com/dominictarr/event-stream/issues/116
https://github.com/indexzero/ps-tree/issues/33

**Comment by samselikoff** [comment]
I don't see the dependency anywhere, I looked at our [yarn.lock from last October](https://github.com/embermap/ember-cli-tailwind/blob/0eeda9f3adccc56cb93c7758f2dd0f1b755a172f/yarn.lock) and I also don't find it.

Could you help me understand how we depend on `event-stream`?

**Comment by ef4** [comment]
The original chain I observed was

ember-cli-tailwind -> tailwindcss -> nodemon -> pstree.remy -> ps-tree -> event-stream

You can reproduce using ember-animated's yarn.lock as of commit a315e4ed014d72a43df567bdbfac0cc8cd20dcbe

But it looks like since then, tailwindcss [decided to remove nodemon](https://github.com/tailwindcss/tailwindcss/pull/440) as their own fix for the vulnerability.

So this is mostly a concern for people who have existing lock files who haven't updated this area recently.

**Comment by samselikoff** [comment]
I see. (I was able to find a version of Ember CLI Tailwind's `yarn.lock` with `event-stream` in it going back much further.)

Any messaging I can or should do for these people?

**Comment by ef4** [comment]
Probably not, the original issue was already shouted pretty loudly and if people didn't hear that they probably won't hear you also shouting about it.
